# Generated by Django 6.0.7 on 2026-07-21 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('co2_saved', models.FloatField()),
                ('icon', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calculated', models.DateTimeField(auto_now_add=True)),
                ('commute_mode', models.CharField(max_length=20)),
                ('flights_per_year', models.IntegerField()),
                ('diet_type', models.CharField(max_length=20)),
                ('electricity_bill', models.CharField(max_length=10)),
                ('shopping_frequency', models.CharField(max_length=20)),
                ('waste_amount', models.CharField(max_length=10)),
                ('transport_kg', models.FloatField()),
                ('food_kg', models.FloatField()),
                ('home_kg', models.FloatField()),
                ('shopping_kg', models.FloatField()),
                ('total_kg', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
